### PR TITLE
fix(adapter-web): use sync OPFS writes for Safari 18.x compatibility

### LINKED ISSUE #905: [Bug]: FileSystemFileHandle.createWritable method not supported on Safari 18.x
### Bug Description

the very nice consolidated `Opfs` effect service introduced in #653 uses the [`FileSystemFileHandle API: createWritable`](https://caniuse.com/mdn-api_filesystemfilehandle_createwritable) method for [`Opfs.writeFile`](https://github.com/livestorejs/livestore/pull/653/files#diff-9f81c2e00eb10079f372cc6dc01e4ca0858cc1292fe40e18b9a8ac753d2eb9b2R154) (and `Opfs.appendToFile`, but that method doesn’t seem to be used anywhere at this point). unfortunately, that method isn’t available for any version of Safari before the latest (v26), which is currently a little over 9% total devices globally (8.5% iOS, 0.89% desktop).

### Minimal Reproduction

the `Opfs.writeFile` method is triggered when the [`cleanupOldStateDbFiles`](https://github.com/livestorejs/livestore/blob/dev/packages/%40livestore/adapter-web/src/web-worker/common/persisted-sqlite.ts#L134) function runs after successful migration. in my case, i got the error to occur by visiting my app in Safari v18.6 while using livestore v0.4.0-dev.19, then upgrading to dev.20, then visiting the app again in Safari v18.6, thereby triggering the migration and `cleanupOldStateDbFiles`.

### LiveStore Version

v0.4.0-dev.20

### Which package(s) are affected?

@livestore/adapter-web

### Environment

```markdown
- OS: macOS 15.6
- Node.js version: v25.2.1
- Package manager: bun v1.3.3
- Runtime: browser
```

### Expected Behavior

i expected the migration to run and my app to load without issue

### Actual Behavior

after seeing:
```
[@livestore/adapter-web:client-session] ✅ Got lock 'livestore-tab-lock-8516a6ff-1f1b-4214-b589-b5e9220a7bca' (clientld: gPwFe, sessionld: tbRsa).
```
logged in the console, i get an error thrown in the console:
```
livestore-worker-8516a6ff-1f1b-4214-b589-b5e9220a7bca-tbRsa] ERROR (#14): @livestore/utils/Web/UnknownError: A web error occurred     sync-backend-D97UzS9U.js:18693
```
and the app gets stuck rendering the livestore provider’s loading UI.

### Error Logs/Screenshots

here’s the error with trace:

```shell
@livestore/utils/Web/UnknownError: A web error occurred
BaseEffectError@http://localhost:5173/node_modules/.vite/deps/sync-backend-D97UzS9U.js:24173:9
Base$2@
klass@http://localhost:5173/node_modules/.vite/deps/sync-backend-D97UzS9U.js:50207:9
TaggedErrorClass@
UnknownError$1@
parseWebError@http://localhost:5173/node_modules/.vite/deps/worker-schema-DJRIeYqj.js:3152:71
    at @livestore/utils:Opfs.writeFile (
)
    at @livestore/adapter-web:cleanupOldStateDbFiles (
)
    at @livestore/adapter-web:worker:InitialMessage {
  [cause]: @livestore/utils/Web/TypeError: { "cause": TypeError: handle.createWritable is not a function. (In 'handle.createWritable(options)', 'handle.createWritable' is undefined) }
  BaseEffectError@http://localhost:5173/node_modules/.vite/deps/sync-backend-D97UzS9U.js:24173:9
  Base$2@
  klass@http://localhost:5173/node_modules/.vite/deps/sync-backend-D97UzS9U.js:50207:9
  TaggedErrorClass@
  TypeError@
  decode@http://localhost:5173/node_modules/.vite/deps/sync-backend-D97UzS9U.js:50226:28
  decode@http://localhost:5173/node_modules/.vite/deps/sync-backend-D97UzS9U.js:47550:69
  @http://localhost:5173/node_modules/.vite/deps/sync-backend-D97UzS9U.js:45212:197
  @http://localhost:5173/node_modules/.vite/deps/sync-backend-D97UzS9U.js:45212:54
  @http://localhost:5173/node_modules/.vite/deps/sync-backend-D97UzS9U.js:45575:38
  @http://localhost:5173/node_modules/.vite/deps/sync-backend-D97UzS9U.js:45212:321
  @http://localhost:5173/node_modules/.vite/deps/sync-backend-D97UzS9U.js:45212:54
  @http://localhost:5173/node_modules/.vite/deps/sync-backend-D97UzS9U.js:45030:60
  parseWebError@http://localhost:5173/node_modules/.vite/deps/worker-schema-DJRIeYqj.js:3149:55 {
    [cause]: TypeError: handle.createWritable is not a function. (In 'handle.createWritable(options)', 'handle.createWritable' is undefined)
    @http://localhost:5173/node_modules/.vite/deps/sync-backend-D97UzS9U.js:15775:14
  }
}
```
Image

### Additional Context

_No response_

### Checklist

- [x] I have searched existing issues to ensure this bug hasn't been reported before
- [x] I have provided a minimal reproduction that demonstrates the issue
- [x] I have included all the requested information above

### PR DESCRIPTION
**Pull request by IGassmann**
## Summary

- Refactored `syncWriteFile` in `utils.ts` to accept `(path: string, data: Uint8Array)` instead of `(handle: FileSystemSyncAccessHandle, buffer: AllowSharedBufferSource)`
- Updated `cleanupOldStateDbFiles` to conditionally use the best available API:
  - `Opfs.writeFile()` (atomic, crash-safe) when `createWritable` is available (Chrome, Firefox, Safari 26+)
  - `Opfs.syncWriteFile()` (non-atomic) as fallback for Safari 18.x compatibility

This fixes the Safari 18.x error where `FileSystemFileHandle.createWritable()` is not available (only supported in Safari 26+). The sync API (`createSyncAccessHandle`) is supported in Safari 15.2+ and works in dedicated workers.

## Test plan

- [x] Verify migration and cleanup works on Safari 18.x
- [x] Verify no regressions on Chrome/Firefox

Fixes #905

### CODE REVIEW

File: packages/@livestore/adapter-web/src/web-worker/common/persisted-sqlite.ts [hunk 1]
```diff
@@ -193,7 +193,9 @@ export const cleanupOldStateDbFiles: (options: {
 
       const archiveFileName = `${Date.now()}-${fileName}`
 
-      yield* Opfs.writeFile(`${opfsDirectory}/archive/${archiveFileName}`, new Uint8Array(archiveFileData))
+      // TODO: Switch to Opfs.writeFile when Safari >= 26 becomes widely available (createWritable support)
+      // for better crash safety (writeFile is atomic, syncWriteFile is not).
+      yield* Opfs.syncWriteFile(`${opfsDirectory}/archive/${archiveFileName}`, new Uint8Array(archiveFileData))
```
Comment (schickling) [inline packages/@livestore/adapter-web/src/web-worker/common/persisted-sqlite.ts]: Wouldn't it make sense here to conditionally check whether the modern API version is available, use that in that case, and otherwise fall back to the synchronous API?

**Review by schickling — APPROVED** [review]
