### PR TITLE
fix: store.subscribe() QueryBuilder support

### LINKED ISSUE #370: `store.subscribe()` Fails in Node.js/Deno Environments
## Summary
`store.subscribe()` throws a `TypeError: Cannot read properties of undefined (reading 'super')` error when used with the `@livestore/adapter-node` adapter in Node.js or Deno environments.

## Environment
- **LiveStore Version**: 0.3.1
- **Runtime**: Deno 2.1.4 (also reproduced in Node.js)
- **Adapter**: `@livestore/adapter-node`
- **Storage**: In-memory (issue also occurs with filesystem storage)
- **Sync**: None (issue occurs even without sync backend)

## Expected Behavior
`store.subscribe()` should work in server-side environments just like `store.query()` and `store.commit()` do.

## Actual Behavior
`store.subscribe()` throws an error in the ReactiveGraph during edge creation:

```
TypeError: Cannot read properties of undefined (reading 'super')
    at ReactiveGraph.addEdge (file:///Users/.../node_modules/@livestore/livestore/0.3.1/dist/reactive.js:259:17)
    at getAtom (file:///Users/.../node_modules/@livestore/livestore/0.3.1/dist/reactive.js:175:26)
    at effect.reactivityGraph.makeEffect.label.label (file:///Users/.../node_modules/@livestore/livestore/0.3.1/dist/store/store.js:198:116)
    at Object.doEffect (file:///Users/.../node_modules/@livestore/livestore/0.3.1/dist/reactive.js:178:17)
    at file:///Users/.../node_modules/@livestore/livestore/0.3.1/dist/store/store.js:206:20
    at NoopTracer.startActiveSpan (file:///Users/.../node_modules/@livestore/utils/0.3.1/dist/NoopTracer.js:49:16)
    at Store.subscribe (file:///Users/.../node_modules/@livestore/livestore/0.3.1/dist/store/store.js:187:54)
```

### ✅ Working Features
- `store.query()` - Works perfectly
- `store.commit()` - Works perfectly  
- `store.shutdown()` - Works perfectly
- `store._dev` helpers - Work perfectly
- All basic store operations

### ❌ Failing Features
- `store.subscribe()` - Fails with reactivity graph error

## Minimal Reproduction

```typescript
import { makeAdapter } from "npm:@livestore/adapter-node";
import { createStorePromise, makeSchema, Events, State, Schema } from "npm:@livestore/livestore";

const events = {
  testEvent: Events.synced({
    name: 'test.TestEvent',
    schema: Schema.Struct({ message: Schema.String }),
  }),
};

const tables = {
  testTable: State.SQLite.table({
    name: 'test_table',
    columns: {
      id: State.SQLite.text({ primaryKey: true }),
      message: State.SQLite.text(),
    },
  }),
};

const materializers = State.SQLite.materializers(events, {
  'test.TestEvent': ({ message }) =>
    tables.testTable.insert({ id: crypto.randomUUID(), message }),
});

const state = State.SQLite.makeState({ tables, materializers });
const schema = makeSchema({ events, state });

const adapter = makeAdapter({
  storage: { type: "in-memory" },
});

const store = await createStorePromise({
  adapter,
  schema,
  storeId: "minimal-repro",
});

// This line fails:
store.subscribe(tables.testTable, (rows) => {
  console.log("Subscription callback:", rows);
});
```

## Additional Context

1. **Server-Side Documentation**: The [server-side clients documentation](https://docs.livestore.dev/reference/syncing/server-side-clients/) only shows `store.query()` usage, not reactive subscriptions.

2. **Reactivity System**: The error occurs in the ReactiveGraph implementation, which seems designed primarily for browser/UI environments.

## Workaround

Currently using polling as a workaround:

```typescript
setInterval(() => {
  const data = store.query(tables.someTable);
  // Process updates
}, 1000);
```

## Questions

1. Is `store.subscribe()` intended to work in server-side environments?
2. If yes, is this a bug in the reactivity system initialization?
3. If no, should the documentation clarify this limitation?
4. Could there be a server-specific subscription API (e.g., `store.onUpdate()`) that doesn't rely on the browser-oriented reactivity system?

## Files for Reproduction

[repro.zip](https://github.com/user-attachments/files/20665608/repro.zip)

- `ultra-minimal-repro.ts` - Minimal failing case
- `works-vs-fails.ts` - Comparison of working vs failing features
- `minimal-repro.ts` - Reproduction with custom schema

Run with: `deno run --allow-all ultra-minimal-repro.ts`

### PR DESCRIPTION
**Pull request by rgbkrk**
primarily to ease doing subscriptions on the server side

Fixes #370.

### Checklist

- [x] I grant to recipients of this Project distribution a perpetual,
non-exclusive, royalty-free, irrevocable copyright license to reproduce, prepare
derivative works of, publicly display, sublicense, and distribute this
Contribution and such derivative works.
- [x] I certify that I am legally entitled to grant this license, and that this
Contribution contains no content requiring a license from any third party.

### CODE REVIEW

**Comment by schickling** [comment]
Thanks a lot @rgbkrk! I'll get this reviewed and merged once I'm back from vacation!

File: packages/@livestore/livestore/src/store/store.ts [hunk 1]
```diff
@@ -311,16 +311,16 @@ export class Store<TSchema extends LiveStoreSchema = LiveStoreSchema, TContext =
   ): Unsubscribe =>
     this.otel.tracer.startActiveSpan(
       `LiveStore.subscribe`,
-      { attributes: { label: options?.label, queryLabel: isQueryBuilder(query) ? undefined : (query as any).label } },
+      { attributes: { label: options?.label, queryLabel: isQueryBuilder(query) ? query.toString() : query.label } },
```
Comment (rgbkrk) [inline packages/@livestore/livestore/src/store/store.ts:314]: Oops, thank you much better.

**Comment by rgbkrk** [comment]
Thanks for cleaning up the rest of the PR and moving it forward. I appreciate being able to read the changes.
